"""Adding friends table

Revision ID: 3cebce45bccd
Revises: 192bbd05b325
Create Date: 2023-03-10 21:59:39.440576

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '3cebce45bccd'
down_revision = '192bbd05b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friends',
                    sa.Column('user', sa.Integer(), nullable=False),
                    sa.Column('friend', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['friend'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user', 'friend')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE user_friends SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_friends')
    # ### end Alembic commands ###
