"""add expenses, comments, and expense_owers tables

Revision ID: 192bbd05b325
Revises: ffdc0a98111c
Create Date: 2023-03-10 15:47:12.343700

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '192bbd05b325'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('split_method', sa.String(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('expense_owers',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('expense_id', sa.Integer(), nullable=True),
    # sa.Column('ower_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    # sa.ForeignKeyConstraint(['ower_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )

    if environment == "production":
        op.execute(f"ALTER TABLE expenses SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
        # op.execute(f"ALTER TABLE expense_owers SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('expense_owers')
    op.drop_table('comments')
    op.drop_table('expenses')
    # ### end Alembic commands ###
