"""empty message

Revision ID: a2a8bf44f300
Revises: 3cebce45bccd
Create Date: 2023-03-12 20:04:22.615269

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'a2a8bf44f300'
down_revision = '3cebce45bccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_owers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('expense_id', sa.Integer(), nullable=False),
                    sa.Column('ower_id', sa.Integer(), nullable=False),
                    sa.Column('amount_to_pay', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
                    sa.ForeignKeyConstraint(['ower_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE expense_owers SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_owers')
    # ### end Alembic commands ###
